server:
  port: 9090
spring:
  application:
    name: data-multidatasource
  batch:
    job:
      enabled: false  
    #initialize-schema: always  #表示让spring batch在数据库里面创建默认的数据表。
      
  datasource:
    src:
      type: com.alibaba.druid.pool.DruidDataSource 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: 123456
      
    dest:
      type: com.alibaba.druid.pool.DruidDataSource 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: 123456
quartz: 
  config:
    quartzs:
    - {batch-job-name: corpJob,job-name: job1,job-group: job-group1,job-class: com.glodon.quartz.job.impl.JobExecuteBatch,trigger-name: trigger1,trigger-group: trigger-group1,cron-expression: '0 /5 * * * ? *' } 
    

      
