server:
  port: 9090
spring:
  application:
    name: data-multidatasource
  datasource:
    src:
      type: com.alibaba.druid.pool.DruidDataSource 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: 123456
      
    dest:
      type: com.alibaba.druid.pool.DruidDataSource 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: 123456
